name: HawkScan
on:
  repository_dispatch:
    types: [integration-initial-test]

permissions:
  contents: read

jobs:
  hawkscan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for stackhawk/hawkscan-action to upload code scanning alert info
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create ${{ github.event.client_payload.repoName }} app directory
        run: mkdir -p common/build/integrationTests/hawkscan-action/apps/${{ github.event.client_payload.repoName }}
      - name: Navigate to ${{ github.event.client_payload.repoName }} app directory
        run: cd common/build/integrationTests/hawkscan-action/apps/${{ github.event.client_payload.repoName }}
      - name: Checkout vulny repo
        run: git clone https://github.com/${{ github.event.client_payload.repoOrg }}/${{ github.event.client_payload.repoName }}.git
      - name: Run ${{ github.event.client_payload.repoName }}
        run: docker-compose up -d
      - name: Navigate to repo root directory
        run: cd /home/runner/work/${{ github.event.client_payload.repoName }}/${{ github.event.client_payload.repoName }}
      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          codeScanningAlerts: true
          githubToken: ${{ github.token }}
          configurationFiles: ${{ github.event.client_payload.configFile }}
          sourceURL: ${{ github.event.client_payload.hawkscanSourceUrl }}
          version: ${{ github.event.client_payload.hawkscanVersion }}
          verbose: ${{ github.event.client_payload.verbose }}
        env:
          # APPLICATION_ID: ${{ github.event.client_payload.appId }}
          APP_ID: ${{ github.event.client_payload.appId }}
